language: node_js
node_js:
  - "11.6.0"
sudo: required
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

script:
  - yarn install
  - yarn build

install:
  - npm install -g firebase-tools

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && firebase deploy --only hosting --token $FIREBASE_TOKEN || echo "Build passed"'

cache:
  yarn: true
